### ISSUE TITLE
Добавить поддержку вывода значений через запятую

### ISSUE THREAD

**Issue by o0** [htmlacademy/demo-console#38]
Интерфейс `console.log` подразумевает, что в вызов можно передать сколько угодно значений через запятую и все они отобразятся, наша консоль, кажется, так не умеет

![screen shot 2017-10-09 at 16 18 45](https://user-images.githubusercontent.com/696826/31340233-2bd35c6e-ad0e-11e7-9260-108d1dbee8e2.png)

**Comment by zeckson** [comment]
Хм, это похоже не регрессию, т.к. такая возможность была всегда

**Comment by o0** [comment]
Вот и я думаю, что это странно.
